# HEAD /posts HTTP/1.1
# HOST: jsonplaceholder.typicode.com

# ###

# GET /posts HTTP/1.1
# HOST: jsonplaceholder.typicode.com

# ###

# POST /posts HTTP/1.1
# Host: jsonplaceholder.typicode.com
# Content-Type: application/json
# Content-Length: 88

# {
#     "title": "Новая публикация",
#     "body": "Текст публикации",
#     "userId": 31337
# }

# ###

# HTTP/1.1 401 Access Denied
# WWW-Authenticate: Basic realm="Protected server"

# ###

# GET /secret-page HTTP/1.1
# Host: myserver.local
# Authorization: Basic YWRtaW46MTIzNDU2

# ###
